# permissions to do edit foos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: foo-editor-role
rules:
- apiGroups:
  - primehub.io
  resources:
  - foos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - foos/status
  verbs:
  - get
  - patch
  - update
