# permissions for end users to edit imagespecjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagespecjob-editor-role
rules:
- apiGroups:
  - primehub.io
  resources:
  - imagespecjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - imagespecjobs/status
  verbs:
  - get
