# permissions for end users to view imagespecjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagespecjob-viewer-role
rules:
- apiGroups:
  - primehub.io
  resources:
  - imagespecjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - primehub.io
  resources:
  - imagespecjobs/status
  verbs:
  - get
