# permissions for end users to edit phapptemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phapptemplate-editor-role
rules:
- apiGroups:
  - primehub.io
  resources:
  - phapptemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - phapptemplates/status
  verbs:
  - get
