# permissions for end users to view phapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phapplication-viewer-role
rules:
- apiGroups:
  - primehub.io
  resources:
  - phapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - primehub.io
  resources:
  - phapplications/status
  verbs:
  - get
