---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - images/finalizers
  verbs:
  - update
- apiGroups:
  - primehub.io
  resources:
  - images/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - primehub.io
  resources:
  - imagespecjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - imagespecjobs/finalizers
  verbs:
  - update
- apiGroups:
  - primehub.io
  resources:
  - imagespecjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - primehub.io
  resources:
  - imagespecs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - imagespecs/finalizers
  verbs:
  - update
- apiGroups:
  - primehub.io
  resources:
  - imagespecs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - primehub.io
  resources:
  - licenses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - licenses/finalizers
  verbs:
  - update
- apiGroups:
  - primehub.io
  resources:
  - licenses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - primehub.io
  resources:
  - phapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - phapplications/finalizers
  verbs:
  - update
- apiGroups:
  - primehub.io
  resources:
  - phapplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - primehub.io
  resources:
  - phdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - phdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - primehub.io
  resources:
  - phdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - primehub.io
  resources:
  - phjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - phjobs/finalizers
  verbs:
  - update
- apiGroups:
  - primehub.io
  resources:
  - phjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - primehub.io
  resources:
  - phschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - phschedules/finalizers
  verbs:
  - update
- apiGroups:
  - primehub.io
  resources:
  - phschedules/status
  verbs:
  - get
  - patch
  - update
