apiVersion: primehub.io/v1alpha1
kind: PhDeployment
metadata:
  name: spam-classifier
  namespace: hub
spec:
  displayName: USER_DEFINED
  userId: "77b7f51c-e559-4ebd-bbc5-1bc74142b64a"
  userName: "phadmin"
  groupName: "phusers"
  groupId: "c49a60f1-3f67-4bdd-8280-a4e6e2860282"
  stop: false # true to stop the seldon deployment;
  description: |
    This is my first deployment.
    This is my first deployment.
    This is my first deployment.
  predictors:
    - name: predictor1
      replicas: 1
      modelImage: infuseai/model-tensorflow2-mnist:v0.1.0
      #modelImage: popcornylu/spam-classifier:1.0.0.1
      instanceType: cpu-1
      metadata: # key-value objects (can update)
        foo: bar
  endpoint:
    accessType: private
    clients:
      - name: test
        token: "$2y$10$ZzEZE/7TenQssFZxpk4YF.Smvn/5LwlawHn1cYhfbYR.mz.BmT5tS"
      - name: root
        token: "$2y$10$TsgIwGQWRT6a78XtG2PvH./lxSOo6fy1rhu4T2DT4B3bHLHs5vMJy"