
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: phdeployments.primehub.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Status
    type: string
  - JSONPath: .status.replicas
    name: Replicas
    type: integer
  - JSONPath: .status.availableReplicas
    name: Available
    type: integer
  group: primehub.io
  names:
    kind: PhDeployment
    listKind: PhDeploymentList
    plural: phdeployments
    singular: phdeployment
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PhDeployment is the Schema for the phdeployments API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PhDeploymentSpec defines the desired state of PhDeployment
          properties:
            description:
              type: string
            displayName:
              type: string
            endpoint:
              properties:
                accessType:
                  type: string
                clients:
                  items:
                    properties:
                      name:
                        type: string
                      token:
                        type: string
                    required:
                    - name
                    - token
                    type: object
                  type: array
              required:
              - accessType
              type: object
            groupId:
              type: string
            groupName:
              type: string
            predictors:
              items:
                properties:
                  imagePullSecret:
                    type: string
                  instanceType:
                    type: string
                  metadata:
                    additionalProperties:
                      type: string
                    type: object
                  modelImage:
                    type: string
                  modelURI:
                    type: string
                  name:
                    type: string
                  replicas:
                    type: integer
                required:
                - instanceType
                - modelImage
                - name
                - replicas
                type: object
              type: array
            stop:
              type: boolean
            updateMessage:
              type: string
            userId:
              type: string
            userName:
              type: string
          required:
          - displayName
          - groupId
          - groupName
          - predictors
          - userId
          - userName
          type: object
        status:
          description: PhDeploymentStatus defines the observed state of PhDeployment
          properties:
            availableReplicas:
              type: integer
            endpoint:
              type: string
            history:
              items:
                properties:
                  spec:
                    description: PhDeploymentSpec defines the desired state of PhDeployment
                    properties:
                      description:
                        type: string
                      displayName:
                        type: string
                      endpoint:
                        properties:
                          accessType:
                            type: string
                          clients:
                            items:
                              properties:
                                name:
                                  type: string
                                token:
                                  type: string
                              required:
                              - name
                              - token
                              type: object
                            type: array
                        required:
                        - accessType
                        type: object
                      groupId:
                        type: string
                      groupName:
                        type: string
                      predictors:
                        items:
                          properties:
                            imagePullSecret:
                              type: string
                            instanceType:
                              type: string
                            metadata:
                              additionalProperties:
                                type: string
                              type: object
                            modelImage:
                              type: string
                            modelURI:
                              type: string
                            name:
                              type: string
                            replicas:
                              type: integer
                          required:
                          - instanceType
                          - modelImage
                          - name
                          - replicas
                          type: object
                        type: array
                      stop:
                        type: boolean
                      updateMessage:
                        type: string
                      userId:
                        type: string
                      userName:
                        type: string
                    required:
                    - displayName
                    - groupId
                    - groupName
                    - predictors
                    - userId
                    - userName
                    type: object
                  time:
                    format: date-time
                    type: string
                required:
                - spec
                - time
                type: object
              type: array
            message:
              type: string
            phase:
              type: string
            replicas:
              type: integer
          required:
          - phase
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
