
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: foos.primehub.io
spec:
  group: primehub.io
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
  scope: ""
  validation:
    openAPIV3Schema:
      description: Foo is the Schema for the foos API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: FooSpec defines the desired state of Foo
          properties:
            foo:
              description: Foo is an example field of Foo. Edit Foo_types.go to remove/update
              type: string
          type: object
        status:
          description: FooStatus defines the observed state of Foo
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
