
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: licenses.primehub.io
spec:
  group: primehub.io
  names:
    kind: License
    listKind: LicenseList
    plural: licenses
    singular: license
  scope: ""
  validation:
    openAPIV3Schema:
      description: License is the Schema for the licenses API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: LicenseSpec defines the desired state of License
          properties:
            signed_license:
              type: string
          required:
          - signed_license
          type: object
        status:
          description: LicenseStatus defines the observed state of License
          properties:
            expired:
              type: string
            expired_at:
              type: string
            licensed_to:
              type: string
            max_group:
              type: string
            max_node:
              type: string
            reason:
              type: string
            started_at:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
