
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: images.primehub.io
spec:
  group: primehub.io
  names:
    kind: Image
    listKind: ImageList
    plural: images
    singular: image
  scope: ""
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            description:
              type: string
            displayName:
              type: string
            groupName:
              type: string
            imageSpec:
              properties:
                baseImage:
                  type: string
                cancel:
                  type: boolean
                packages:
                  properties:
                    apt:
                      items:
                        type: string
                      type: array
                    conda:
                      items:
                        type: string
                      type: array
                    pip:
                      items:
                        type: string
                      type: array
                  type: object
                pullSecret:
                  type: string
                updateTime:
                  format: date-time
                  type: string
              required:
              - baseImage
              type: object
            pullSecret:
              type: string
            type:
              type: string
            url:
              type: string
            urlForGpu:
              type: string
          type: object
        status:
          properties:
            jobCondition:
              properties:
                image:
                  type: string
                jobName:
                  type: string
                phase:
                  type: string
              required:
              - image
              - jobName
              - phase
              type: object
          required:
          - jobCondition
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
