
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: imagespecs.primehub.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: status of current job
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: primehub.io
  names:
    kind: ImageSpec
    listKind: ImageSpecList
    plural: imagespecs
    singular: imagespec
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            baseImage:
              type: string
            packages:
              properties:
                apt:
                  items:
                    type: string
                  type: array
                conda:
                  items:
                    type: string
                  type: array
                pip:
                  items:
                    type: string
                  type: array
              type: object
            pullSecret:
              type: string
            updateTime:
              format: date-time
              type: string
          required:
          - baseImage
          - packages
          type: object
        status:
          properties:
            image:
              type: string
            jobName:
              type: string
            phase:
              type: string
          required:
          - image
          - jobName
          - phase
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
