# permissions for end users to edit phdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phdeployment-editor-role
rules:
- apiGroups:
  - primehub.io
  resources:
  - phdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - phdeployments/status
  verbs:
  - get
