# permissions for end users to view phdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phdeployment-viewer-role
rules:
- apiGroups:
  - primehub.io
  resources:
  - phdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - primehub.io
  resources:
  - phdeployments/status
  verbs:
  - get
