# permissions for end users to view phjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phjob-viewer-role
rules:
- apiGroups:
  - primehub.io
  resources:
  - phjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - primehub.io
  resources:
  - phjobs/status
  verbs:
  - get
