# permissions for end users to edit phjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phjob-editor-role
rules:
- apiGroups:
  - primehub.io
  resources:
  - phjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - phjobs/status
  verbs:
  - get
