---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - licenses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - licenses/finalizers
  verbs:
  - update
- apiGroups:
  - primehub.io
  resources:
  - licenses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - primehub.io
  resources:
  - phdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - phdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - primehub.io
  resources:
  - phdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - primehub.io
  resources:
  - phjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - phjobs/finalizers
  verbs:
  - update
- apiGroups:
  - primehub.io
  resources:
  - phjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - primehub.io
  resources:
  - phschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primehub.io
  resources:
  - phschedules/finalizers
  verbs:
  - update
- apiGroups:
  - primehub.io
  resources:
  - phschedules/status
  verbs:
  - get
  - patch
  - update
